// ============================================================
//  PROSPEO — Internationalisation (i18n)
//  9 langues : fr, en, es, pt, it, de, no, sv, nl
// ============================================================

export const LANGUAGES = [
  { code: "fr", label: "Français",    flag: "🇫🇷" },
  { code: "en", label: "English",     flag: "🇬🇧" },
  { code: "es", label: "Español",     flag: "🇪🇸" },
  { code: "pt", label: "Português",   flag: "🇵🇹" },
  { code: "it", label: "Italiano",    flag: "🇮🇹" },
  { code: "de", label: "Deutsch",     flag: "🇩🇪" },
  { code: "no", label: "Norsk",       flag: "🇳🇴" },
  { code: "sv", label: "Svenska",     flag: "🇸🇪" },
  { code: "nl", label: "Nederlands",  flag: "🇳🇱" },
  { code: "zh", label: "中文",         flag: "🇨🇳" },
];

export const translations = {

  // ── AUTH ──────────────────────────────────────────────────
  login:               { fr:"Connexion",       en:"Sign in",        es:"Iniciar sesión",  pt:"Entrar",         it:"Accedi",          de:"Anmelden",       no:"Logg inn",       sv:"Logga in",       nl:"Inloggen"        , zh:"登录" },
  register:            { fr:"Créer un compte", en:"Create account", es:"Crear cuenta",   pt:"Criar conta",    it:"Crea account",    de:"Konto erstellen",no:"Opprett konto",  sv:"Skapa konto",    nl:"Account aanmaken", zh:"创建账户" },
  email:               { fr:"Email",           en:"Email",          es:"Correo",         pt:"E-mail",         it:"Email",           de:"E-Mail",         no:"E-post",         sv:"E-post",         nl:"E-mail"          , zh:"电子邮件" },
  password:            { fr:"Mot de passe",    en:"Password",       es:"Contraseña",     pt:"Senha",          it:"Password",        de:"Passwort",       no:"Passord",        sv:"Lösenord",       nl:"Wachtwoord"      , zh:"密码" },
  signout:             { fr:"Déconnexion",     en:"Sign out",       es:"Cerrar sesión",  pt:"Sair",           it:"Esci",            de:"Abmelden",       no:"Logg ut",        sv:"Logga ut",       nl:"Uitloggen"       , zh:"退出" },
  no_account:          { fr:"Pas encore de compte ?", en:"No account yet?", es:"¿Sin cuenta?", pt:"Sem conta?", it:"Nessun account?", de:"Noch kein Konto?", no:"Ingen konto?", sv:"Inget konto?", nl:"Nog geen account?" , zh:"还没有账户？" },
  already_account:     { fr:"Déjà un compte ?", en:"Already have an account?", es:"¿Ya tienes cuenta?", pt:"Já tem conta?", it:"Hai già un account?", de:"Bereits ein Konto?", no:"Har du allerede konto?", sv:"Har du redan ett konto?", nl:"Al een account?" , zh:"已有账户？" },

  // ── NAVIGATION ────────────────────────────────────────────
  nav_home:            { fr:"Accueil",         en:"Home",           es:"Inicio",         pt:"Início",         it:"Home",            de:"Startseite",     no:"Hjem",           sv:"Hem",            nl:"Home"            , zh:"首页" },
  nav_add:             { fr:"Ajouter",         en:"Add",            es:"Agregar",        pt:"Adicionar",      it:"Aggiungi",        de:"Hinzufügen",     no:"Legg til",       sv:"Lägg till",      nl:"Toevoegen"       , zh:"添加" },
  nav_prospects:       { fr:"Prospects",       en:"Prospects",      es:"Prospectos",     pt:"Prospectos",     it:"Prospetti",       de:"Interessenten",  no:"Prospekter",     sv:"Prospekter",     nl:"Prospects"       , zh:"客户" },
  nav_reports:         { fr:"Rapports",        en:"Reports",        es:"Informes",       pt:"Relatórios",     it:"Rapporti",        de:"Berichte",       no:"Rapporter",      sv:"Rapporter",      nl:"Rapporten"       , zh:"报告" },
  nav_profile:         { fr:"Mon profil",      en:"My profile",     es:"Mi perfil",      pt:"Meu perfil",     it:"Il mio profilo",  de:"Mein Profil",    no:"Min profil",     sv:"Min profil",     nl:"Mijn profiel"    , zh:"我的资料" },
  nav_subscription:    { fr:"Abonnement",      en:"Subscription",   es:"Suscripción",    pt:"Assinatura",     it:"Abbonamento",     de:"Abonnement",     no:"Abonnement",     sv:"Prenumeration",  nl:"Abonnement"      , zh:"订阅" },
  nav_crm:             { fr:"CRM",             en:"CRM",            es:"CRM",            pt:"CRM",            it:"CRM",             de:"CRM",            no:"CRM",            sv:"CRM",            nl:"CRM"             , zh:"CRM" },
  nav_superadmin:      { fr:"Super Admin",     en:"Super Admin",    es:"Super Admin",    pt:"Super Admin",    it:"Super Admin",     de:"Super Admin",    no:"Super Admin",    sv:"Super Admin",    nl:"Super Admin"     , zh:"超级管理员" },
  nav_language:        { fr:"Langue",          en:"Language",       es:"Idioma",         pt:"Idioma",         it:"Lingua",          de:"Sprache",        no:"Språk",          sv:"Språk",          nl:"Taal"            , zh:"语言" },

  // ── DASHBOARD ────────────────────────────────────────────
  dashboard_title:     { fr:"Tableau de bord", en:"Dashboard",      es:"Panel",          pt:"Painel",         it:"Dashboard",       de:"Dashboard",      no:"Kontrollpanel",  sv:"Instrumentpanel",nl:"Dashboard"       , zh:"仪表板" },
  last_prospects:      { fr:"Derniers prospects", en:"Latest prospects", es:"Últimos prospectos", pt:"Últimos prospectos", it:"Ultimi prospetti", de:"Letzte Interessenten", no:"Siste prospekter", sv:"Senaste prospekter", nl:"Laatste prospects" , zh:"最新客户" },
  quick_actions:       { fr:"Actions rapides", en:"Quick actions",  es:"Acciones rápidas", pt:"Ações rápidas", it:"Azioni rapide",  de:"Schnellaktionen",no:"Hurtighandlinger",sv:"Snabbåtgärder",  nl:"Snelle acties"   , zh:"快速操作" },
  total:               { fr:"Total",           en:"Total",          es:"Total",          pt:"Total",          it:"Totale",          de:"Gesamt",         no:"Totalt",         sv:"Totalt",         nl:"Totaal"          , zh:"总计" },
  hot:                 { fr:"Chauds",          en:"Hot",            es:"Calientes",      pt:"Quentes",        it:"Caldi",           de:"Heiß",           no:"Varme",          sv:"Heta",           nl:"Heet"            , zh:"热门" },
  converted:           { fr:"Convertis",       en:"Converted",      es:"Convertidos",    pt:"Convertidos",    it:"Convertiti",      de:"Konvertiert",    no:"Konvertert",     sv:"Konverterade",   nl:"Geconverteerd"   , zh:"已转化" },
  this_week:           { fr:"Semaine",         en:"This week",      es:"Esta semana",    pt:"Esta semana",    it:"Questa settimana",de:"Diese Woche",    no:"Denne uken",     sv:"Denna vecka",    nl:"Deze week"       , zh:"本周" },
  by_sales_rep:        { fr:"Par commercial",  en:"By sales rep",   es:"Por comercial",  pt:"Por vendedor",   it:"Per commerciale", de:"Pro Vertreter",  no:"Per selger",     sv:"Per säljare",    nl:"Per vertegenw."  , zh:"按销售员" },

  // ── ADD PROSPECT ─────────────────────────────────────────
  add_title:           { fr:"Nouveau prospect", en:"New prospect",  es:"Nuevo prospecto",pt:"Novo prospecto", it:"Nuovo prospetto", de:"Neuer Interessent",no:"Ny prospekt",  sv:"Ny prospekt",    nl:"Nieuwe prospect" , zh:"新客户" },
  manual:              { fr:"Manuel",          en:"Manual",         es:"Manual",         pt:"Manual",         it:"Manuale",         de:"Manuell",        no:"Manuell",        sv:"Manuell",        nl:"Handmatig"       , zh:"手动" },
  card_ai:             { fr:"Carte IA",        en:"AI Card",        es:"Tarjeta IA",     pt:"Cartão IA",      it:"Biglietto IA",    de:"KI-Karte",       no:"IA-kort",        sv:"AI-kort",        nl:"AI-kaart"        , zh:"AI名片" },
  vocal:               { fr:"Vocal",           en:"Voice",          es:"Voz",            pt:"Voz",            it:"Voce",            de:"Sprache",        no:"Stemme",         sv:"Röst",           nl:"Stem"            , zh:"语音" },
  first_name:          { fr:"Prénom",          en:"First name",     es:"Nombre",         pt:"Primeiro nome",  it:"Nome",            de:"Vorname",        no:"Fornavn",        sv:"Förnamn",        nl:"Voornaam"        , zh:"名" },
  last_name:           { fr:"Nom",             en:"Last name",      es:"Apellido",       pt:"Sobrenome",      it:"Cognome",         de:"Nachname",       no:"Etternavn",      sv:"Efternamn",      nl:"Achternaam"      , zh:"姓" },
  company:             { fr:"Entreprise",      en:"Company",        es:"Empresa",        pt:"Empresa",        it:"Azienda",         de:"Unternehmen",    no:"Bedrift",        sv:"Företag",        nl:"Bedrijf"         , zh:"公司" },
  role:                { fr:"Poste",           en:"Role",           es:"Cargo",          pt:"Cargo",          it:"Ruolo",           de:"Position",       no:"Stilling",       sv:"Roll",           nl:"Functie"         , zh:"职位" },
  phone:               { fr:"Téléphone",       en:"Phone",          es:"Teléfono",       pt:"Telefone",       it:"Telefono",        de:"Telefon",        no:"Telefon",        sv:"Telefon",        nl:"Telefoon"        , zh:"电话" },
  notes:               { fr:"Notes",           en:"Notes",          es:"Notas",          pt:"Notas",          it:"Note",            de:"Notizen",        no:"Notater",        sv:"Anteckningar",   nl:"Notities"        , zh:"备注" },
  save_prospect:       { fr:"Enregistrer le prospect", en:"Save prospect", es:"Guardar prospecto", pt:"Salvar prospecto", it:"Salva prospetto", de:"Interessent speichern", no:"Lagre prospekt", sv:"Spara prospekt", nl:"Prospect opslaan" , zh:"保存客户" },
  saving:              { fr:"Enregistrement...", en:"Saving...",    es:"Guardando...",   pt:"Salvando...",    it:"Salvataggio...",  de:"Speichern...",   no:"Lagrer...",      sv:"Sparar...",      nl:"Opslaan..."      , zh:"保存中..." },
  status:              { fr:"Statut",          en:"Status",         es:"Estado",         pt:"Status",         it:"Stato",           de:"Status",         no:"Status",         sv:"Status",         nl:"Status"          , zh:"状态" },

  // ── STATUS LABELS ─────────────────────────────────────────
  status_chaud:        { fr:"Chaud",           en:"Hot",            es:"Caliente",       pt:"Quente",         it:"Caldo",           de:"Heiß",           no:"Varm",           sv:"Het",            nl:"Heet"            , zh:"热" },
  status_tiede:        { fr:"Tiède",           en:"Warm",           es:"Tibio",          pt:"Morno",          it:"Tiepido",         de:"Warm",           no:"Lunken",         sv:"Ljummen",        nl:"Lauw"            , zh:"温" },
  status_froid:        { fr:"Froid",           en:"Cold",           es:"Frío",           pt:"Frio",           it:"Freddo",          de:"Kalt",           no:"Kald",           sv:"Kall",           nl:"Koud"            , zh:"冷" },
  status_converti:     { fr:"Converti",        en:"Converted",      es:"Convertido",     pt:"Convertido",     it:"Convertito",      de:"Konvertiert",    no:"Konvertert",     sv:"Konverterad",    nl:"Geconverteerd"   , zh:"已转化" },

  // ── DETAIL VIEW ───────────────────────────────────────────
  back:                { fr:"← Retour",        en:"← Back",         es:"← Volver",       pt:"← Voltar",       it:"← Indietro",      de:"← Zurück",       no:"← Tilbake",      sv:"← Tillbaka",     nl:"← Terug"         , zh:"← 返回" },
  edit:                { fr:"✏️ Modifier",     en:"✏️ Edit",        es:"✏️ Editar",      pt:"✏️ Editar",      it:"✏️ Modifica",     de:"✏️ Bearbeiten",  no:"✏️ Rediger",     sv:"✏️ Redigera",    nl:"✏️ Bewerken"     , zh:"✏️ 编辑" },
  edit_prospect:       { fr:"Modifier le prospect", en:"Edit prospect", es:"Editar prospecto", pt:"Editar prospecto", it:"Modifica prospetto", de:"Interessent bearbeiten", no:"Rediger prospekt", sv:"Redigera prospekt", nl:"Prospect bewerken" , zh:"编辑客户" },
  save:                { fr:"✅ Enregistrer",  en:"✅ Save",         es:"✅ Guardar",      pt:"✅ Salvar",       it:"✅ Salva",         de:"✅ Speichern",    no:"✅ Lagre",        sv:"✅ Spara",        nl:"✅ Opslaan"       , zh:"✅ 保存" },
  cancel:              { fr:"Annuler",         en:"Cancel",         es:"Cancelar",       pt:"Cancelar",       it:"Annulla",         de:"Abbrechen",      no:"Avbryt",         sv:"Avbryt",         nl:"Annuleren"       , zh:"取消" },
  delete_prospect:     { fr:"🗑 Supprimer ce prospect", en:"🗑 Delete this prospect", es:"🗑 Eliminar prospecto", pt:"🗑 Excluir prospecto", it:"🗑 Elimina prospetto", de:"🗑 Interessent löschen", no:"🗑 Slett prospekt", sv:"🗑 Ta bort prospekt", nl:"🗑 Prospect verwijderen" , zh:"🗑 删除此客户" },
  edit_status:         { fr:"Modifier le statut", en:"Change status", es:"Cambiar estado", pt:"Alterar status", it:"Cambia stato",   de:"Status ändern",  no:"Endre status",   sv:"Ändra status",   nl:"Status wijzigen" , zh:"更改状态" },
  ai_synthesis:        { fr:"Synthèse IA",     en:"AI Summary",     es:"Resumen IA",     pt:"Resumo IA",      it:"Sintesi IA",      de:"KI-Zusammenfassung",no:"IA-sammendrag",sv:"AI-sammanfattning",nl:"AI-samenvatting" , zh:"AI摘要" },
  generate:            { fr:"✨ Générer",       en:"✨ Generate",     es:"✨ Generar",      pt:"✨ Gerar",        it:"✨ Genera",        de:"✨ Generieren",   no:"✨ Generer",      sv:"✨ Generera",     nl:"✨ Genereren"     , zh:"✨ 生成" },

  // ── REPORT ────────────────────────────────────────────────
  report_title:        { fr:"Rapport & Export", en:"Report & Export", es:"Informe y Export", pt:"Relatório e Export", it:"Report ed Export", de:"Bericht & Export", no:"Rapport & Eksport", sv:"Rapport & Export", nl:"Rapport & Export" , zh:"报告与导出" },
  period:              { fr:"Période",          en:"Period",          es:"Período",        pt:"Período",        it:"Periodo",         de:"Zeitraum",       no:"Periode",        sv:"Period",         nl:"Periode"         , zh:"时期" },
  today:               { fr:"Aujourd'hui",      en:"Today",           es:"Hoy",            pt:"Hoje",           it:"Oggi",            de:"Heute",          no:"I dag",          sv:"Idag",           nl:"Vandaag"         , zh:"今天" },
  yesterday:           { fr:"Hier",             en:"Yesterday",       es:"Ayer",           pt:"Ontem",          it:"Ieri",            de:"Gestern",        no:"I går",          sv:"Igår",           nl:"Gisteren"        , zh:"昨天" },
  this_week_label:     { fr:"Cette semaine",    en:"This week",       es:"Esta semana",    pt:"Esta semana",    it:"Questa settimana",de:"Diese Woche",    no:"Denne uken",     sv:"Denna vecka",    nl:"Deze week"       , zh:"本周" },
  this_month:          { fr:"Ce mois",          en:"This month",      es:"Este mes",       pt:"Este mês",       it:"Questo mese",     de:"Dieser Monat",   no:"Denne måneden",  sv:"Denna månad",    nl:"Deze maand"      , zh:"本月" },
  custom:              { fr:"Personnalisé",     en:"Custom",          es:"Personalizado",  pt:"Personalizado",  it:"Personalizzato",  de:"Benutzerdefiniert",no:"Tilpasset",    sv:"Anpassad",       nl:"Aangepast"       , zh:"自定义" },
  export_excel:        { fr:"📥 Exporter Excel", en:"📥 Export Excel", es:"📥 Exportar Excel", pt:"📥 Exportar Excel", it:"📥 Esporta Excel", de:"📥 Excel exportieren", no:"📥 Eksporter Excel", sv:"📥 Exportera Excel", nl:"📥 Excel exporteren" , zh:"📥 导出Excel" },
  send_report:         { fr:"📧 Envoyer rapport", en:"📧 Send report", es:"📧 Enviar informe", pt:"📧 Enviar relatório", it:"📧 Invia report", de:"📧 Bericht senden", no:"📧 Send rapport", sv:"📧 Skicka rapport", nl:"📧 Rapport sturen" , zh:"📧 发送报告" },
  no_prospects:        { fr:"Aucun prospect sur cette période", en:"No prospects in this period", es:"Sin prospectos en este período", pt:"Sem prospectos neste período", it:"Nessun prospetto in questo periodo", de:"Keine Interessenten in diesem Zeitraum", no:"Ingen prospekter i denne perioden", sv:"Inga prospekter under denna period", nl:"Geen prospects in deze periode" , zh:"此期间无客户" },
  filter_by_rep:       { fr:"Filtrer par commercial", en:"Filter by sales rep", es:"Filtrar por comercial", pt:"Filtrar por vendedor", it:"Filtra per commerciale", de:"Nach Vertreter filtern", no:"Filtrer etter selger", sv:"Filtrera efter säljare", nl:"Filteren op vertegenw." , zh:"按销售员筛选" },
  all:                 { fr:"Tous",             en:"All",             es:"Todos",          pt:"Todos",          it:"Tutti",           de:"Alle",           no:"Alle",           sv:"Alla",           nl:"Alle"            , zh:"全部" },
  by_source:           { fr:"Par source",       en:"By source",       es:"Por fuente",     pt:"Por fonte",      it:"Per fonte",       de:"Nach Quelle",    no:"Etter kilde",    sv:"Efter källa",    nl:"Op bron"         , zh:"按来源" },

  // ── PROFILE ───────────────────────────────────────────────
  profile_title:       { fr:"Mon profil",       en:"My profile",      es:"Mi perfil",      pt:"Meu perfil",     it:"Il mio profilo",  de:"Mein Profil",    no:"Min profil",     sv:"Min profil",     nl:"Mijn profiel"    , zh:"我的资料" },
  personal_info:       { fr:"Informations personnelles", en:"Personal information", es:"Información personal", pt:"Informações pessoais", it:"Informazioni personali", de:"Persönliche Informationen", no:"Personlig informasjon", sv:"Personlig information", nl:"Persoonlijke informatie" , zh:"个人信息" },
  profile_updated:     { fr:"✅ Profil mis à jour !", en:"✅ Profile updated!", es:"✅ Perfil actualizado!", pt:"✅ Perfil atualizado!", it:"✅ Profilo aggiornato!", de:"✅ Profil aktualisiert!", no:"✅ Profil oppdatert!", sv:"✅ Profil uppdaterad!", nl:"✅ Profiel bijgewerkt!" , zh:"✅ 资料已更新！" },
  save_profile:        { fr:"Enregistrer mon profil", en:"Save my profile", es:"Guardar mi perfil", pt:"Salvar meu perfil", it:"Salva il mio profilo", de:"Mein Profil speichern", no:"Lagre profilen min", sv:"Spara min profil", nl:"Mijn profiel opslaan" , zh:"保存资料" },
  email_readonly:      { fr:"L'email ne peut pas être modifié", en:"Email cannot be changed", es:"El correo no se puede cambiar", pt:"O e-mail não pode ser alterado", it:"L'email non può essere modificata", de:"E-Mail kann nicht geändert werden", no:"E-post kan ikke endres", sv:"E-post kan inte ändras", nl:"E-mail kan niet worden gewijzigd" , zh:"邮箱不可更改" },
  language_label:      { fr:"Langue de l'interface", en:"Interface language", es:"Idioma de la interfaz", pt:"Idioma da interface", it:"Lingua dell'interfaccia", de:"Sprache der Benutzeroberfläche", no:"Grensesnittspråk", sv:"Gränssnittsspråk", nl:"Interfacetaal" , zh:"界面语言" },

  // ── SUBSCRIPTION ─────────────────────────────────────────
  sub_title:           { fr:"Mon abonnement",   en:"My subscription", es:"Mi suscripción", pt:"Minha assinatura",it:"Il mio abbonamento",de:"Mein Abonnement",no:"Mitt abonnement",sv:"Mitt abonnemang",nl:"Mijn abonnement" , zh:"我的订阅" },
  sub_status:          { fr:"Statut actuel",    en:"Current status",  es:"Estado actual",  pt:"Status atual",   it:"Stato attuale",   de:"Aktueller Status",no:"Gjeldende status",sv:"Nuvarande status",nl:"Huidige status"  , zh:"当前状态" },
  trial_active:        { fr:"🎁 Essai gratuit", en:"🎁 Free trial",   es:"🎁 Prueba gratis",pt:"🎁 Teste grátis", it:"🎁 Prova gratuita",de:"🎁 Kostenlose Testversion",no:"🎁 Gratis prøveperiode",sv:"🎁 Gratis provperiod",nl:"🎁 Gratis proefperiode" , zh:"🎁 免费试用" },
  subscribe:           { fr:"S'abonner",        en:"Subscribe",       es:"Suscribirse",    pt:"Assinar",        it:"Abbonati",        de:"Abonnieren",     no:"Abonner",        sv:"Prenumerera",    nl:"Abonneren"       , zh:"订阅" },
  activate_key:        { fr:"🔑 Activer une clé", en:"🔑 Activate a key", es:"🔑 Activar clave", pt:"🔑 Ativar chave", it:"🔑 Attiva chiave", de:"🔑 Schlüssel aktivieren", no:"🔑 Aktiver nøkkel", sv:"🔑 Aktivera nyckel", nl:"🔑 Sleutel activeren" , zh:"🔑 激活密钥" },
  activate_btn:        { fr:"🔑 Activer mon abonnement", en:"🔑 Activate my subscription", es:"🔑 Activar mi suscripción", pt:"🔑 Ativar minha assinatura", it:"🔑 Attiva il mio abbonamento", de:"🔑 Mein Abonnement aktivieren", no:"🔑 Aktiver abonnementet mitt", sv:"🔑 Aktivera mitt abonnemang", nl:"🔑 Mijn abonnement activeren" , zh:"🔑 激活我的订阅" },
  free_trial_days:     { fr:"Essai gratuit 7 jours", en:"Free trial 7 days", es:"Prueba gratuita 7 días", pt:"Teste gratuito 7 dias", it:"Prova gratuita 7 giorni", de:"7 Tage kostenlos testen", no:"7 dagers gratis prøveperiode", sv:"7 dagars gratis provperiod", nl:"7 dagen gratis proberen" , zh:"7天免费试用" },
  per_month:           { fr:"/ mois",           en:"/ month",         es:"/ mes",          pt:"/ mês",          it:"/ mese",          de:"/ Monat",        no:"/ måned",        sv:"/ månad",        nl:"/ maand"         , zh:"/ 月" },
  per_year:            { fr:"/ an",             en:"/ year",          es:"/ año",          pt:"/ ano",          it:"/ anno",          de:"/ Jahr",         no:"/ år",           sv:"/ år",           nl:"/ jaar"          , zh:"/ 年" },

  // ── CRM ───────────────────────────────────────────────────
  crm_title:           { fr:"Intégration CRM",  en:"CRM Integration", es:"Integración CRM",pt:"Integração CRM", it:"Integrazione CRM",de:"CRM-Integration", no:"CRM-integrering",sv:"CRM-integration", nl:"CRM-integratie"  , zh:"CRM集成" },
  crm_connect:         { fr:"+ Connecter un CRM", en:"+ Connect a CRM", es:"+ Conectar CRM", pt:"+ Conectar CRM", it:"+ Connetti CRM",  de:"+ CRM verbinden",no:"+ Koble til CRM", sv:"+ Anslut CRM",    nl:"+ CRM verbinden" , zh:"+ 连接CRM" },
  crm_type:            { fr:"Votre CRM",        en:"Your CRM",        es:"Su CRM",         pt:"Seu CRM",        it:"Il tuo CRM",      de:"Ihr CRM",        no:"Ditt CRM",       sv:"Ditt CRM",       nl:"Uw CRM"          , zh:"您的CRM" },

  // ── GENERAL ───────────────────────────────────────────────
  loading:             { fr:"Chargement...",    en:"Loading...",      es:"Cargando...",    pt:"Carregando...",  it:"Caricamento...",  de:"Laden...",       no:"Laster...",      sv:"Laddar...",      nl:"Laden..."        , zh:"加载中..." },
  error:               { fr:"Erreur",           en:"Error",           es:"Error",          pt:"Erro",           it:"Errore",          de:"Fehler",         no:"Feil",           sv:"Fel",            nl:"Fout"            , zh:"错误" },
  success:             { fr:"Succès",           en:"Success",         es:"Éxito",          pt:"Sucesso",        it:"Successo",        de:"Erfolg",         no:"Suksess",        sv:"Framgång",       nl:"Succes"          , zh:"成功" },
  search:              { fr:"Rechercher...",    en:"Search...",       es:"Buscar...",      pt:"Pesquisar...",   it:"Cerca...",        de:"Suchen...",      no:"Søk...",         sv:"Sök...",         nl:"Zoeken..."       , zh:"搜索..." },
  confirm_delete:      { fr:"Supprimer ce prospect ?", en:"Delete this prospect?", es:"¿Eliminar este prospecto?", pt:"Excluir este prospecto?", it:"Eliminare questo prospetto?", de:"Diesen Interessenten löschen?", no:"Slette denne prospekten?", sv:"Ta bort denna prospekt?", nl:"Dit prospect verwijderen?" , zh:"删除此客户？" },
  date:                { fr:"Date",             en:"Date",            es:"Fecha",          pt:"Data",           it:"Data",            de:"Datum",          no:"Dato",           sv:"Datum",          nl:"Datum"           , zh:"日期" },
  manager_label:       { fr:"👑 Manager",       en:"👑 Manager",      es:"👑 Manager",     pt:"👑 Manager",     it:"👑 Manager",      de:"👑 Manager",     no:"👑 Manager",     sv:"👑 Manager",     nl:"👑 Manager"      , zh:"👑 经理" },
  commercial_label:    { fr:"Commercial",       en:"Sales rep",       es:"Comercial",      pt:"Vendedor",       it:"Commerciale",     de:"Vertreter",      no:"Selger",         sv:"Säljare",        nl:"Vertegenw."      , zh:"销售员" },
  analyzing:           { fr:"Analyse IA...",    en:"AI analyzing...", es:"Analizando IA...",pt:"Analisando IA...",it:"Analisi IA...",  de:"KI analysiert...",no:"IA analyserer...",sv:"AI analyserar...",nl:"AI analyseert..." , zh:"AI分析中..." },

  // ── ADD VIEW — vocal & misc ──────────────────────────────
  vocal_unavailable:   { fr:"Vocal non disponible",      en:"Voice unavailable",        es:"Voz no disponible",      pt:"Voz indisponível",       it:"Voce non disponibile",    de:"Sprache nicht verfügbar", no:"Stemme utilgjengelig",   sv:"Röst ej tillgänglig",    nl:"Stem nicht beschikbaar",  zh:"语音不可用"               },
  open_in_chrome:      { fr:"Ouvrir dans Chrome",         en:"Open in Chrome",           es:"Abrir en Chrome",        pt:"Abrir no Chrome",        it:"Apri in Chrome",          de:"In Chrome öffnen",        no:"Åpne i Chrome",          sv:"Öppna i Chrome",         nl:"Openen in Chrome",       zh:"在Chrome中打开"            },
  vocal_not_supported: { fr:"Vocal non supporté",         en:"Voice not supported",      es:"Voz no compatible",      pt:"Voz não suportada",      it:"Voce non supportata",     de:"Sprache nicht unterstützt",no:"Stemme støttes ikke",   sv:"Röst stöds inte",        nl:"Stem niet ondersteund",  zh:"不支持语音"                },
  vocal_dictation:     { fr:"Dictée vocale",              en:"Voice dictation",          es:"Dictado de voz",         pt:"Ditado de voz",          it:"Dettatura vocale",        de:"Spracheingabe",           no:"Stemmedikte ring",        sv:"Röstdiktering",          nl:"Stemdicteren",           zh:"语音听写"                  },
  listening:           { fr:"Écoute en cours...",         en:"Listening...",             es:"Escuchando...",          pt:"Ouvindo...",             it:"In ascolto...",           de:"Hören...",                no:"Lytter...",               sv:"Lyssnar...",             nl:"Luisteren...",           zh:"聆听中..."                },
  ready_to_listen:     { fr:"Prêt à écouter",             en:"Ready to listen",          es:"Listo para escuchar",   pt:"Pronto para ouvir",      it:"Pronto ad ascoltare",     de:"Bereit zum Zuhören",      no:"Klar til å lytte",        sv:"Redo att lyssna",        nl:"Klaar om te luisteren",  zh:"准备聆听"                  },
  paste_or_type:       { fr:"Collez ou tapez ici...",     en:"Paste or type here...",    es:"Pegue o escriba aquí...",pt:"Cole ou digite aqui...", it:"Incolla o digita qui...", de:"Hier einfügen/eingeben...",no:"Lim inn eller skriv...",  sv:"Klistra in eller skriv...",nl:"Plak of typ hier...",   zh:"在此粘贴或输入..."           },
  no_text_analyze:     { fr:"Aucun texte à analyser",     en:"No text to analyze",       es:"Sin texto para analizar", pt:"Sem texto para analisar",it:"Nessun testo da analizzare",de:"Kein Text zu analysieren",no:"Ingen tekst å analysere",sv:"Ingen text att analysera", nl:"Geen tekst om te analyseren",zh:"没有要分析的文本"             },
  duplicate_own:       { fr:"Prospect déjà dans votre base", en:"Prospect already in your database", es:"Prospecto ya en su base", pt:"Prospecto já na sua base", it:"Prospetto già nel database", de:"Interessent bereits in Ihrer Datenbank", no:"Prospekt allerede i din database", sv:"Prospekt redan i din databas", nl:"Prospect al in uw database", zh:"客户已在您的数据库中"          },
  duplicate_other:     { fr:"Prospect déjà enregistré",   en:"Prospect already registered", es:"Prospecto ya registrado", pt:"Prospecto já registrado", it:"Prospetto già registrato", de:"Interessent bereits registriert", no:"Prospekt allerede registrert", sv:"Prospekt redan registrerat", nl:"Prospect al geregistreerd", zh:"客户已被注册"                },
  yourself:            { fr:"vous-même",                  en:"yourself",                 es:"usted mismo",            pt:"você mesmo",             it:"te stesso",               de:"sich selbst",             no:"deg selv",               sv:"dig själv",              nl:"uzelf",                  zh:"您自己"                    },
  initial_status:      { fr:"Statut initial",             en:"Initial status",           es:"Estado inicial",         pt:"Status inicial",         it:"Stato iniziale",          de:"Anfangsstatus",           no:"Innledende status",      sv:"Inledande status",       nl:"Beginstatus",            zh:"初始状态"                  },
  vocal_pwa_msg:       { fr:"La dictée vocale n'est pas disponible depuis l'app raccourci iPhone. Elle fonctionne uniquement dans", en:"Voice dictation is not available from the iPhone shortcut app. It only works in", es:"El dictado de voz no está disponible desde el acceso directo de iPhone. Solo funciona en", pt:"O ditado de voz não está disponível no atalho do iPhone. Funciona apenas no", it:"La dettatura vocale non è disponibile dall'app collegamento iPhone. Funziona solo in", de:"Spracheingabe ist in der iPhone-Verknüpfung nicht verfügbar. Funktioniert nur in", no:"Stemmedikte ring er ikke tilgjengelig fra iPhone-snarveien. Fungerer kun i", sv:"Röstdiktering är inte tillgänglig från iPhone-genvägen. Fungerar bara i", nl:"Stemdicteren is niet beschikbaar vanuit de iPhone-snelkoppeling. Werkt alleen in", zh:"iPhone快捷方式不支持语音听写，仅在以下环境中可用：" },
  prospect_added:      { fr:"ajouté !",                   en:"added!",                   es:"añadido!",               pt:"adicionado!",            it:"aggiunto!",               de:"hinzugefügt!",            no:"lagt til!",              sv:"tillagd!",               nl:"toegevoegd!",            zh:"已添加！"                  },
  // ── DASHBOARD banners ────────────────────────────────────
  subscribe_cta:       { fr:"Abonnez-vous pour continuer à utiliser Prospeo", en:"Subscribe to keep using Prospeo", es:"Suscríbase para continuar usando Prospeo", pt:"Assine para continuar usando o Prospeo", it:"Abbonati per continuare a usare Prospeo", de:"Abonnieren Sie, um Prospeo weiter zu nutzen", no:"Abonner for å fortsette å bruke Prospeo", sv:"Prenumerera för att fortsätta använda Prospeo", nl:"Abonneer om Prospeo te blijven gebruiken", zh:"订阅以继续使用Prospeo" },
  activate_cta:        { fr:"Activez votre abonnement pour ne pas perdre vos données", en:"Activate your subscription to keep your data", es:"Active su suscripción para conservar sus datos", pt:"Ative sua assinatura para manter seus dados", it:"Attiva il tuo abbonamento per conservare i dati", de:"Aktivieren Sie Ihr Abonnement, um Ihre Daten zu behalten", no:"Aktiver abonnementet for å beholde dataene dine", sv:"Aktivera din prenumeration för att behålla dina data", nl:"Activeer uw abonnement om uw gegevens te bewaren", zh:"激活订阅以保留您的数据" },
  see_plans:           { fr:"Voir les offres",          en:"See plans",           es:"Ver planes",           pt:"Ver planos",           it:"Vedi piani",           de:"Pläne ansehen",        no:"Se planer",           sv:"Se planer",           nl:"Plannen bekijken",     zh:"查看计划"         },

  // ── SUPERADMIN KPIs ───────────────────────────────────────
  kpi_active:          { fr:"Actifs",                   en:"Active",             es:"Activos",             pt:"Ativos",              it:"Attivi",              de:"Aktiv",                no:"Aktive",             sv:"Aktiva",             nl:"Actief",              zh:"活跃"             },
  kpi_trials:          { fr:"Essais",                   en:"Trials",             es:"Pruebas",             pt:"Testes",              it:"Prove",               de:"Testversionen",        no:"Prøveperioder",      sv:"Testperioder",       nl:"Proeven",             zh:"试用"             },
  kpi_expired:         { fr:"Expirés",                  en:"Expired",            es:"Expirados",           pt:"Expirados",           it:"Scaduti",             de:"Abgelaufen",           no:"Utløpt",             sv:"Utgångna",           nl:"Verlopen",            zh:"已过期"           },
  kpi_cancelled:       { fr:"Annulées",                 en:"Cancelled",          es:"Cancelados",          pt:"Cancelados",          it:"Annullati",           de:"Storniert",            no:"Kansellert",         sv:"Avbrutna",           nl:"Geannuleerd",         zh:"已取消"           },
  kpi_licences:        { fr:"Licences payantes",        en:"Paid licences",      es:"Licencias de pago",   pt:"Licenças pagas",      it:"Licenze a pagamento", de:"Bezahlte Lizenzen",    no:"Betalte lisenser",   sv:"Betalda licenser",   nl:"Betaalde licenties",  zh:"付费许可证"       },
  kpi_companies:       { fr:"Entreprises",              en:"Companies",          es:"Empresas",            pt:"Empresas",            it:"Aziende",             de:"Unternehmen",          no:"Bedrifter",          sv:"Företag",            nl:"Bedrijven",           zh:"企业"             },
  kpi_users:           { fr:"Utilisateurs",             en:"Users",              es:"Usuarios",            pt:"Usuários",            it:"Utenti",              de:"Benutzer",             no:"Brukere",            sv:"Användare",          nl:"Gebruikers",          zh:"用户"             },
  kpi_total_users:     { fr:"Utilisateurs totaux",      en:"Total users",        es:"Usuarios totales",    pt:"Usuários totais",     it:"Utenti totali",       de:"Gesamtbenutzer",       no:"Totalt brukere",     sv:"Totalt användare",   nl:"Totaal gebruikers",   zh:"总用户数"         },
  kpi_total_companies: { fr:"Total entreprises",        en:"Total companies",    es:"Total empresas",      pt:"Total empresas",      it:"Totale aziende",      de:"Unternehmen gesamt",   no:"Totalt bedrifter",   sv:"Totalt företag",     nl:"Totaal bedrijven",    zh:"总企业数"         },
  kpi_total_keys:      { fr:"Total générées",           en:"Total generated",    es:"Total generadas",     pt:"Total geradas",       it:"Totale generate",     de:"Gesamt generiert",     no:"Totalt generert",    sv:"Totalt genererat",   nl:"Totaal gegenereerd",  zh:"总生成数"         },
  kpi_used_keys:       { fr:"Utilisées",                en:"Used",               es:"Usadas",              pt:"Usadas",              it:"Usate",               de:"Verwendet",            no:"Brukte",             sv:"Använda",            nl:"Gebruikt",            zh:"已使用"           },
  kpi_unused_keys:     { fr:"Disponibles",              en:"Available",          es:"Disponibles",         pt:"Disponíveis",         it:"Disponibili",         de:"Verfügbar",            no:"Tilgjengelige",      sv:"Tillgängliga",       nl:"Beschikbaar",         zh:"可用"             },
  kpi_expired_keys:    { fr:"Expirées (inutilisées)",   en:"Expired (unused)",   es:"Expiradas (sin usar)", pt:"Expiradas (sem uso)", it:"Scadute (non usate)", de:"Abgelaufen (unbenutzt)",no:"Utløpt (ubrukte)", sv:"Utgångna (oanvända)",nl:"Verlopen (ongebruikt)",zh:"已过期(未用)"     },
  kpi_lifetime:        { fr:"À vie (offertes)",         en:"Lifetime (free)",    es:"De por vida (gratis)", pt:"Vitalícia (grátis)", it:"A vita (gratis)",     de:"Lebenslang (gratis)",  no:"Livstid (gratis)",   sv:"Livstid (gratis)",   nl:"Levenslang (gratis)", zh:"终身(免费)"       },
  kpi_avg_licences:    { fr:"Licences moy. / entreprise", en:"Avg licences / company", es:"Lic. prom. / empresa", pt:"Lic. méd. / empresa", it:"Lic. medie / azienda", de:"Durchschn. Lic. / Untern.", no:"Gj.snitt lis. / bedr.", sv:"Gns. lic. / företag", nl:"Gem. lic. / bedrijf", zh:"平均许可证/企业"   },
  kpi_state:           { fr:"État des licences",        en:"Licence status",     es:"Estado de licencias", pt:"Estado das licenças", it:"Stato delle licenze", de:"Lizenzstatus",         no:"Lisensstat us",      sv:"Licensstatus",       nl:"Licentiestatus",      zh:"许可证状态"       },
  kpi_expiring_soon:   { fr:"Essais expirant sous 7j",  en:"Trials expiring in 7d", es:"Pruebas que expiran en 7d", pt:"Testes expirando em 7d", it:"Prove in scadenza 7g", de:"Tests ablaufend in 7T", no:"Prøver utløper om 7d", sv:"Tester löper ut om 7d", nl:"Proeven verlopen in 7d", zh:"7天内到期试用"    },
  kpi_add_licences:    { fr:"Ajouter des licences à une entreprise existante", en:"Add licences to existing company", es:"Agregar licencias a empresa existente", pt:"Adicionar licenças à empresa existente", it:"Aggiungi licenze ad azienda esistente", de:"Lizenzen zu bestehendem Unternehmen hinzufügen", no:"Legg til lisenser til eksisterende bedrift", sv:"Lägg till licenser till befintligt företag", nl:"Licenties toevoegen aan bestaand bedrijf", zh:"向现有企业添加许可证" },
  kpi_select_company:  { fr:"Sélectionnez une entreprise", en:"Select a company", es:"Seleccione una empresa", pt:"Selecione uma empresa", it:"Seleziona un'azienda", de:"Unternehmen auswählen", no:"Velg en bedrift", sv:"Välj ett företag", nl:"Selecteer een bedrijf", zh:"选择企业"          },
  kpi_generating:      { fr:"Génération...",             en:"Generating...",      es:"Generando...",        pt:"Gerando...",          it:"Generando...",        de:"Generieren...",        no:"Genererer...",       sv:"Genererar...",       nl:"Genereren...",        zh:"生成中..."        },
  kpi_copied:          { fr:"Clé copiée !",              en:"Key copied!",        es:"¡Clave copiada!",     pt:"Chave copiada!",      it:"Chiave copiata!",     de:"Schlüssel kopiert!",   no:"Nøkkel kopiert!",    sv:"Nyckel kopierad!",   nl:"Sleutel gekopieerd!", zh:"密钥已复制！"     },
  kpi_disabled:        { fr:"Compte désactivé",          en:"Account disabled",   es:"Cuenta desactivada",  pt:"Conta desativada",    it:"Account disabilitato",de:"Konto deaktiviert",    no:"Konto deaktivert",   sv:"Konto inaktiverat",  nl:"Account uitgeschakeld",zh:"账户已禁用"       },
  kpi_superadmin_sub:  { fr:"Tableau de bord de gestion — accès exclusif", en:"Management dashboard — exclusive access", es:"Panel de gestión — acceso exclusivo", pt:"Painel de gestão — acesso exclusivo", it:"Dashboard di gestione — accesso esclusivo", de:"Verwaltungs-Dashboard — exklusiver Zugang", no:"Administrasjonsdashboard — eksklusiv tilgang", sv:"Administrationspanel — exklusiv åtkomst", nl:"Beheerdashboard — exclusieve toegang", zh:"管理控制台 — 专属访问"  },

  // ── CRM LOCKED VIEW ──────────────────────────────────────
  crm_locked_title:    { fr:"Option CRM — Sur devis",    en:"CRM Option — On quote",    es:"Opción CRM — Bajo presupuesto", pt:"Opção CRM — Sob orçamento", it:"Opzione CRM — Su preventivo", de:"CRM Option — Auf Anfrage", no:"CRM-alternativ — Etter tilbud", sv:"CRM-alternativ — På offert", nl:"CRM-optie — Op offerte", zh:"CRM选项 — 按报价" },
  crm_locked_desc:     { fr:"L'intégration CRM est une option payante disponible sur devis. Elle permet de synchroniser automatiquement vos prospects avec HubSpot, Salesforce, Pipedrive, Zoho et Odoo.", en:"CRM integration is a paid option available on quote. It allows automatic synchronization of your prospects with HubSpot, Salesforce, Pipedrive, Zoho and Odoo.", es:"La integración CRM es una opción de pago disponible bajo presupuesto. Permite sincronizar automáticamente sus prospectos con HubSpot, Salesforce, Pipedrive, Zoho y Odoo.", pt:"A integração CRM é uma opção paga disponível sob orçamento. Permite sincronizar automaticamente seus prospectos com HubSpot, Salesforce, Pipedrive, Zoho e Odoo.", it:"L'integrazione CRM è un'opzione a pagamento disponibile su preventivo. Consente la sincronizzazione automatica dei tuoi prospetti con HubSpot, Salesforce, Pipedrive, Zoho e Odoo.", de:"Die CRM-Integration ist eine kostenpflichtige Option auf Anfrage. Sie ermöglicht die automatische Synchronisierung Ihrer Interessenten mit HubSpot, Salesforce, Pipedrive, Zoho und Odoo.", no:"CRM-integrasjon er et betalt alternativ tilgjengelig på tilbud. Det muliggjør automatisk synkronisering av prospektene dine med HubSpot, Salesforce, Pipedrive, Zoho og Odoo.", sv:"CRM-integration är ett betalt alternativ tillgängligt på offert. Det möjliggör automatisk synkronisering av dina prospekter med HubSpot, Salesforce, Pipedrive, Zoho och Odoo.", nl:"CRM-integratie is een betaalde optie beschikbaar op offerte. Het maakt automatische synchronisatie van uw prospects met HubSpot, Salesforce, Pipedrive, Zoho en Odoo mogelijk.", zh:"CRM集成是一项按报价提供的付费选项，可自动将您的潜在客户与HubSpot、Salesforce、Pipedrive、Zoho和Odoo同步。" },
  crm_base_plan:       { fr:"Forfait de base",           en:"Base plan",                es:"Plan base",              pt:"Plano base",            it:"Piano base",              de:"Basisplan",               no:"Basisplan",              sv:"Basplan",                nl:"Basisplan",              zh:"基础套餐"         },
  crm_on_quote:        { fr:"Sur devis",                 en:"On quote",                 es:"Bajo presupuesto",       pt:"Sob orçamento",         it:"Su preventivo",           de:"Auf Anfrage",             no:"Etter tilbud",           sv:"På offert",              nl:"Op offerte",              zh:"按报价"           },
  crm_setup_fee:       { fr:"Frais d'accès et de paramétrage", en:"Setup & access fee", es:"Tarifa de instalación",  pt:"Taxa de configuração",  it:"Tariffa di configurazione",de:"Einrichtungsgebühr",     no:"Installasjonsfee",       sv:"Installationsavgift",    nl:"Installatiekosten",      zh:"安装费"           },
  crm_contact_admin:   { fr:"Contactez votre administrateur Prospeo pour activer cette option.", en:"Contact your Prospeo administrator to activate this option.", es:"Contacte a su administrador de Prospeo para activar esta opción.", pt:"Contate seu administrador Prospeo para ativar esta opção.", it:"Contatta il tuo amministratore Prospeo per attivare questa opzione.", de:"Wenden Sie sich an Ihren Prospeo-Administrator, um diese Option zu aktivieren.", no:"Kontakt din Prospeo-administrator for å aktivere dette alternativet.", sv:"Kontakta din Prospeo-administratör för att aktivera det här alternativet.", nl:"Neem contact op met uw Prospeo-beheerder om deze optie te activeren.", zh:"请联系您的Prospeo管理员以激活此选项。" },
  crm_request_quote:   { fr:"📧 Demander un devis",      en:"📧 Request a quote",       es:"📧 Solicitar presupuesto",pt:"📧 Solicitar orçamento", it:"📧 Richiedere un preventivo",de:"📧 Angebot anfordern",  no:"📧 Be om tilbud",        sv:"📧 Begär offert",        nl:"📧 Offerte aanvragen",   zh:"📧 请求报价"      },

  // ── MANAGER DASHBOARD ────────────────────────────────────
  nav_mgr:             { fr:"Objectifs",          en:"Objectives",       es:"Objetivos",        pt:"Objetivos",        it:"Obiettivi",         de:"Ziele",             no:"Mål",               sv:"Mål",               nl:"Doelstellingen",   zh:"目标"             },
  mgr_title:           { fr:"Tableau de bord Manager", en:"Manager Dashboard", es:"Panel del Manager", pt:"Painel do Manager", it:"Dashboard Manager", de:"Manager-Dashboard", no:"Manager-dashboard", sv:"Chefsdashboard",    nl:"Manager dashboard", zh:"经理仪表板"        },
  mgr_objectives:      { fr:"Objectifs",          en:"Objectives",       es:"Objetivos",        pt:"Objetivos",        it:"Obiettivi",         de:"Ziele",             no:"Mål",               sv:"Mål",               nl:"Doelstellingen",   zh:"目标"             },
  mgr_set_obj:         { fr:"Définir les objectifs", en:"Set objectives", es:"Definir objetivos", pt:"Definir objetivos", it:"Definire obiettivi", de:"Ziele festlegen",  no:"Sett mål",          sv:"Sätt mål",          nl:"Doelen instellen", zh:"设定目标"          },
  mgr_monthly:         { fr:"Mensuel",             en:"Monthly",          es:"Mensual",          pt:"Mensal",           it:"Mensile",           de:"Monatlich",         no:"Månedlig",          sv:"Månadsvis",         nl:"Maandelijks",      zh:"月度"             },
  mgr_quarterly:       { fr:"Trimestriel",         en:"Quarterly",        es:"Trimestral",       pt:"Trimestral",       it:"Trimestrale",       de:"Vierteljährlich",   no:"Kvartalsvis",       sv:"Kvartalsvis",       nl:"Kwartaal",         zh:"季度"             },
  mgr_annual:          { fr:"Annuel",              en:"Annual",           es:"Anual",            pt:"Anual",            it:"Annuale",           de:"Jährlich",          no:"Årlig",             sv:"Årsvis",            nl:"Jaarlijks",        zh:"年度"             },
  mgr_period_week:     { fr:"Cette semaine",       en:"This week",        es:"Esta semana",      pt:"Esta semana",      it:"Questa settimana",  de:"Diese Woche",       no:"Denne uken",        sv:"Denna vecka",       nl:"Deze week",        zh:"本周"             },
  mgr_period_month:    { fr:"Ce mois",             en:"This month",       es:"Este mes",         pt:"Este mês",         it:"Questo mese",       de:"Dieser Monat",      no:"Denne måneden",     sv:"Denna månad",       nl:"Deze maand",       zh:"本月"             },
  mgr_conversion:      { fr:"Taux de conversion",  en:"Conversion rate",  es:"Tasa de conversión", pt:"Taxa de conversão", it:"Tasso di conversione", de:"Konversionsrate", no:"Konverteringsrate", sv:"Konverteringsgrad", nl:"Conversiepercentage", zh:"转化率"          },
  mgr_prospects_added: { fr:"Prospects ajoutés",   en:"Prospects added",  es:"Prospectos agregados", pt:"Prospectos adicionados", it:"Prospetti aggiunti", de:"Interessenten hinzugefügt", no:"Lagt til prospekter", sv:"Tillagda prospekter", nl:"Toegevoegde prospects", zh:"已添加客户"      },
  mgr_objective_lbl:   { fr:"Objectif",            en:"Objective",        es:"Objetivo",         pt:"Objetivo",         it:"Obiettivo",         de:"Ziel",              no:"Mål",               sv:"Mål",               nl:"Doel",             zh:"目标"             },
  mgr_progress:        { fr:"Progression",         en:"Progress",         es:"Progreso",         pt:"Progresso",        it:"Progresso",         de:"Fortschritt",       no:"Fremgang",          sv:"Framsteg",          nl:"Voortgang",        zh:"进度"             },
  mgr_save_obj:        { fr:"✅ Enregistrer les objectifs", en:"✅ Save objectives", es:"✅ Guardar objetivos", pt:"✅ Salvar objetivos", it:"✅ Salva obiettivi", de:"✅ Ziele speichern", no:"✅ Lagre mål",       sv:"✅ Spara mål",       nl:"✅ Doelen opslaan", zh:"✅ 保存目标"       },
  mgr_per_rep:         { fr:"Par commercial",      en:"Per sales rep",    es:"Por comercial",    pt:"Por vendedor",     it:"Per commerciale",   de:"Pro Vertreter",     no:"Per selger",        sv:"Per säljare",       nl:"Per vertegenw.",   zh:"按销售员"          },
  mgr_obj_saved:       { fr:"✅ Objectifs enregistrés !", en:"✅ Objectives saved!", es:"✅ ¡Objetivos guardados!", pt:"✅ Objetivos salvos!", it:"✅ Obiettivi salvati!", de:"✅ Ziele gespeichert!", no:"✅ Mål lagret!", sv:"✅ Mål sparade!", nl:"✅ Doelen opgeslagen!", zh:"✅ 目标已保存！" },

};

// ── Detect browser language ────────────────────────────────
export function detectBrowserLang() {
  const supported = LANGUAGES.map(l => l.code);
  const nav = navigator.language || navigator.userLanguage || "fr";
  const code = nav.split("-")[0].toLowerCase();
  return supported.includes(code) ? code : "fr";
}

// ── Get saved language ─────────────────────────────────────
export function getSavedLang() {
  return localStorage.getItem("prospeo_lang") || null;
}

// ── Save language ──────────────────────────────────────────
export function saveLang(code) {
  localStorage.setItem("prospeo_lang", code);
}

// ── Translation hook helper ────────────────────────────────
export function t(key, lang) {
  const entry = translations[key];
  if (!entry) return key;
  return entry[lang] || entry["fr"] || key;
}
